### PR TITLE
unloosen the style

### PR DESCRIPTION
**Pull request by jamesgorrie**
Add anything so that some people might have something to discuss.

### CODE REVIEW

**Comment by phamann** [comment]
I was thinking as we may have multiple languages in here, this should go in a `js/` sub-directory.

**Comment by phamann** [comment]
:+1: Other than comments. Thanks for kicking this off!

**Comment by jamesgorrie** [comment]
Done - but I don't have permission to merge.

**Comment by phamann** [comment]
You should now :smile:

**Pull request merged**
